version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
